### ISSUE TITLE
Usage of your repo

### ISSUE THREAD

**Issue by billinux** [mokote/vagrantboxes#2]
Hi,

I install your debian7 box with vagrant.

How to use the config files in your repo concerning debian7 ?
Could you explain how to use and configure your debian box

Best regards

**Comment by billinux** [comment]
Could you give me the root password for debian7 please

**Comment by sashka** [comment]
box according to `debian-7/preseed.cfg`. You may use user "vagrant" with password "vagrant" (or simply "vagrant ssh") and "sudo" then. 

All config files are specific for Packer, so please take a look at packer.io for detailed docs.
